image: node:18.17

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - mv env.example .env

test_job:
  script:
    - npm run test
    - tar -czf allure-results.tar.gz reports/

  artifacts:
    paths:
      - "allure-results.tar.gz"
    when: always
    expire_in: "30 days"

  only:
    - master